version: '3.7'
services: 
  nginx: 
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front
      - gateway
  front: 
    image: imallinson/feedback-forms-front
  gateway:
    image: imallinson/feedback-forms-gateway
  accounts: 
    image: imallinson/feedback-forms-accounts
  cohorts:
    image: imallinson/feedback-forms-cohorts
  submit: 
    image: imallinson/feedback-forms-submit
  retriever:
    image: imallinson/feedback-forms-retriever
  consumer: 
    image: imallinson/feedback-forms-consumer
  mongo:
    image: mongo
  queue:
    image: webcenter/activemq
