version: '3.7'
services: 
  nginx: 
   image: nginx
   volumes:
     - "./nginx.conf:/etc/nginx/nginx.conf"
   ports:
     - "80:80"
     - "443:443"
   depends_on:
     - front 
     - accounts
     - submit
     - display
  front: 
    image: feedback-forms-front
    build: ./feedback-forms-front
  accounts: 
    image: feedback-forms-accounts
    build: ./feedback-forms-accounts
    depends_on: 
      - consumer
  submit: 
    image: feedback-forms-submit
    build: ./feedback-forms-submit
    depends_on: 
      - consumer
  display: 
    image: feedback-forms-display
    build: ./feedback-forms-display
    depends_on: 
      - consumer
  consumer: 
    image: feedback-forms-consumer
    build: ./feedback-forms-consumer
    depends_on: 
      - mongo
      - queue
  mongo:
    image: mongo
  queue:
    image: webcenter/activemq
