version: '3.7'
services: 
  nginx: 
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front 
  front: 
    image: feedback-forms-front
    build: ./feedback-forms-front
  gateway:
    image: feedback-forms-gateway
    build: ./feedback-forms-gateway
  accounts: 
    image: feedback-forms-accounts
    build: ./feedback-forms-accounts
  submit: 
    image: feedback-forms-submit
    build: ./feedback-forms-submit
  display: 
    image: feedback-forms-display
    build: ./feedback-forms-display
  consumer: 
    image: feedback-forms-consumer
    build: ./feedback-forms-consumer
    depends_on: 
      - mongo
      - queue
  mongo:
    image: mongo
  queue:
    image: webcenter/activemq
